### ISSUE TITLE
allow Win32-2.13

### ISSUE THREAD

**Issue by robx** [haskellari/postgresql-libpq#24]
Hackage has [Win32-2.13.2.1](https://hackage.haskell.org/package/Win32-2.13.2.1/changelog) with what appear to be changes unrelated to how it's used in postgresql-libpq.

(I ran into this in a [CI build](https://github.com/PostgREST/postgrest/runs/7249188990?check_suite_focus=true) with current stackage nightly, failing with

```
Error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for postgresql-libpq-0.9.4.3:
Win32-2.12.0.1 from stack configuration does not match >=2.2.0.2 && <2.11  (latest matching
                   version is 2.10.1.1)
needed due to postgrest-9.0.1.20220630 -> postgresql-libpq-0.9.4.3
```

A build with `allow-newer` is in process [here](https://github.com/PostgREST/postgrest/runs/7249640729?check_suite_focus=true), which compiled `postgresql-libpq` successfully with `Win32-2.12.0.1`.)

**Comment by phadej** [comment]
Done in #29
