### ISSUE TITLE
Allow Cabal-3.8

### ISSUE THREAD

**Issue by ysangkok** [haskellari/postgresql-libpq#26]
Tested using

```diff
 custom-setup
   setup-depends:
       base   >=4.3  && <5
-    , Cabal  >=1.10 && <3.7
+    , Cabal  >=1.10 && <3.9
```

**Comment by avanov** [comment]
Why is there an upper bound if `Setup.hs` doesn't have this upper bound applied to the setup logic? This check is destined to fail each time there's a new major GHC release without visible benefits, and it's not possible to override the bound with `allow-newer` on the receiving side of the package.

**Comment by ysangkok** [comment]
>  it's not possible to override the bound with allow-newer on the receiving side of the package.

What do you mean? This works on Cabal 3.8.1.0 and GHC 9.4.2:

    cabal get postgresql-libpq
    cd postgresql-libpq*
    cabal repl --allow-newer=postgresql-libpq:base,postgresql-libpq:Cabal

**Comment by avanov** [comment]
yeah, I've checked it too and it turned out that I left a freeze file from a previous GHC version and it affected the build plan by disregarding `allow-newer`, but I interpreted it as if `allow-newer` wasn't affecting `setup-depends` the same way as `build-depends`. False report on my side.

**Comment by phadej** [comment]
Done in #29
