### ISSUE TITLE
Please make it build with ghc-9.10

### ISSUE THREAD

**Issue by erikd** [haskellari/postgresql-libpq#60]
There is currently a `base >=4.12.0.0 && <4.20` dependency in the cabal file.

**Comment by phadej** [comment]
See #59. Blocked on https://github.com/haskell/cabal/issues/9885

**Comment by erikd** [comment]
Does this unblock things: https://github.com/haskell/cabal/issues/9885#issuecomment-2197425247

**Comment by phadej** [comment]
@erikd yes

**Comment by erikd** [comment]
Is there any ETA for an update to this?
