### ISSUE TITLE
"libpq" constraint of 14.12 seems needlessly high

### ISSUE THREAD

**Issue by nikita-volkov** [haskellari/postgresql-libpq#66]
Which leads to failed builds on systems that are compatible. E.g.,

```
...
checking for the PostgreSQL version... 14.11
checking if PostgreSQL version 14.11 is >= 14.12... no
configure: error: Library requirements (PostgreSQL) not met.
Error: [Cabal-7125]
Failed to build postgresql-libpq-configure-0.11 (which is required by hasql-1.8). See the build log above for details.
```

Judging by [the official docs](https://www.postgresql.org/docs/current/libpq-pipeline-mode.html), pipelining is supported in libpq starting from version 14.

**Comment by phadej** [comment]
What's your system running 14.11? Could you upgrade the libpq?

Ubuntu Jammy has 14.13: https://packages.ubuntu.com/jammy/postgresql-14-asn1oid, and I picked 14.12 because that's one installed on GHA Windows CI.

I'm hesitant to use anything I don't test against. 14.13 is the last in 14. series, so perfectly I'd like to require that, unfortunately I have to allow 14.12 for now.

**Comment by nikita-volkov** [comment]
Locally I'm running on macOS via brew. It's not a problem to update.

In some situations however it's easier to avoid upgrading the lib than a system dependency. E.g., in my case at work I may have to go thru long communications with colleagues before that can be achieved. So I'm sure more people will be coming with the same request.

**Comment by phadej** [comment]
If Ubuntu LTS 22 managed to upgrade promptly to `libpq-14.13`, I'm quite convinced that the long communications doesn't need to be long. If corporate processes make it easier to have a local patch to (just released) `postgresql-libpq` than upgrading `libpq` (released before), i'm not sorry.

**Comment by nikita-volkov** [comment]
Ok. Up to you

**Comment by phadej** [comment]
- 14.13 is released recently, 2024-08-08. 
- 14.12 2024-05-09
- 14.11 2024-02-08

Looks like PostgreSQL has 3 month minor release cycle.

---

I checked that
- [debian bookworm](https://packages.debian.org/bookworm/libpq-dev) atm bundles 15.8 released 2024-08-08
- [fedora 40](https://packages.fedoraproject.org/pkgs/libpq/libpq/) bundles 16.4 also released 2024-08-08

so big distributions are promptly including the new minor releases.

---

GHA windows image https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md (atm) image version is 20240825.1.0, and includes 14.12 released 2024-05-09

---

Until there is technical reason why upgrade is not possible, I don't see a reason to relax lower bound. As far as I can see the postgresql version adoption is quite prompt in free software.

**Comment by phadej** [comment]
@echatav No. `postgresql-libpq` definitely needs postgres 14.
