### ISSUE TITLE
accept uris of the form postgresql://user:password@host:port/dbname

### ISSUE THREAD

**Issue by teto** [haskellari/postgresql-libpq#68]
hi,

all tools I work with (psql, dbeaver, rainfrog, lazysql) accept connection uris of the form `postgresql://user:password@host:port/dbname` as described in https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING.

I might have missed it but I could not find a reference on haddock.

Also if I might add https://hackage.haskell.org/package/postgresql-libpq-0.10.2.0/docs/Database-PostgreSQL-LibPQ.html#v:connectdb doesn't explicitly tell what string to use to connect, one has to look at libpq documentation to understand what to pass (ie "user=toto password=zozo dbname=mydb")

**Comment by phadej** [comment]
postgresql-libpq is a thin wrapper over libpq, it calls `PQconnectdb` with given parameter directly.

So the URI argument should work if underlying libpq supports it.
